version: '3'

vars:
  PYTHON: python3
  ALIGN_SCRIPT: align_keymap.py
  CONFIG_DIR: config
  TESTS_DIR: tests

  # Corne
  CORNE_KEYMAP: "{{.CONFIG_DIR}}/corne.keymap"
  CORNE_LAYOUT: corne_layout.json
  CORNE_DRAWER_YAML: corne_keymap.yaml
  CORNE_SVG: corne_keymap.svg
  CORNE_JPG: corne_keymap.jpg

  # Glove80
  GLOVE80_KEYMAP: "{{.CONFIG_DIR}}/glove80.keymap"
  GLOVE80_LAYOUT: glove80_layout.json
  GLOVE80_DRAWER_YAML: glove80_keymap.yaml
  GLOVE80_SVG: glove80_keymap.svg
  GLOVE80_JPG: glove80_keymap.jpg

  # Piantor
  PIANTOR_KEYMAP: "{{.CONFIG_DIR}}/piantor_pro_bt.keymap"
  PIANTOR_LAYOUT: piantor_layout.json
  PIANTOR_DRAWER_YAML: piantor_keymap.yaml
  PIANTOR_SVG: piantor_keymap.svg
  PIANTOR_JPG: piantor_keymap.jpg

  # Testing
  PYTEST_FILE: "{{.TESTS_DIR}}/test_align_keymap.py"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================================
  # Alignment Tasks
  # ============================================================================

  align-glove80:
    desc: Align Glove80 keymap
    sources:
      - "{{.GLOVE80_KEYMAP}}"
      - "{{.GLOVE80_LAYOUT}}"
    cmds:
      - "{{.PYTHON}} {{.ALIGN_SCRIPT}} --keymap {{.GLOVE80_KEYMAP}} --layout {{.GLOVE80_LAYOUT}}"
      - echo "✅ Glove80 keymap aligned"

  align-corne:
    desc: Align Corne keymap
    sources:
      - "{{.CORNE_KEYMAP}}"
      - "{{.CORNE_LAYOUT}}"
    cmds:
      - "{{.PYTHON}} {{.ALIGN_SCRIPT}} --keymap {{.CORNE_KEYMAP}} --layout {{.CORNE_LAYOUT}}"
      - echo "✅ Corne keymap aligned"

  align-piantor:
    desc: Align Piantor keymap
    sources:
      - "{{.PIANTOR_KEYMAP}}"
      - "{{.PIANTOR_LAYOUT}}"
    cmds:
      - "{{.PYTHON}} {{.ALIGN_SCRIPT}} --keymap {{.PIANTOR_KEYMAP}} --layout {{.PIANTOR_LAYOUT}}"
      - echo "✅ Piantor keymap aligned"

  align:
    desc: Align all keymaps
    deps:
      - align-glove80
      - align-corne
      - align-piantor

  # ============================================================================
  # Drawing Tasks
  # ============================================================================

  draw-glove80:
    desc: Generate Glove80 SVG from YAML
    sources:
      - "{{.GLOVE80_DRAWER_YAML}}"
    generates:
      - "{{.GLOVE80_SVG}}"
      - "{{.GLOVE80_JPG}}"
    cmds:
      - keymap -c keymap_drawer.config.yaml draw {{.GLOVE80_DRAWER_YAML}} > {{.GLOVE80_SVG}}
      - echo "✅ {{.GLOVE80_SVG}}"
      - magick {{.GLOVE80_SVG}} {{.GLOVE80_JPG}}
      - echo "✅ {{.GLOVE80_JPG}}"

  draw-corne:
    desc: Generate Corne SVG from YAML
    sources:
      - "{{.CORNE_DRAWER_YAML}}"
    generates:
      - "{{.CORNE_SVG}}"
      - "{{.CORNE_JPG}}"
    cmds:
      - keymap -c keymap_drawer.config.yaml draw {{.CORNE_DRAWER_YAML}} > {{.CORNE_SVG}}
      - echo "✅ {{.CORNE_SVG}}"
      - magick {{.CORNE_SVG}} {{.CORNE_JPG}}
      - echo "✅ {{.CORNE_JPG}}"

  draw-piantor:
    desc: Generate Piantor SVG from YAML
    sources:
      - "{{.PIANTOR_DRAWER_YAML}}"
    generates:
      - "{{.PIANTOR_SVG}}"
      - "{{.PIANTOR_JPG}}"
    cmds:
      - keymap -c keymap_drawer.config.yaml draw {{.PIANTOR_DRAWER_YAML}} > {{.PIANTOR_SVG}}
      - echo "✅ {{.PIANTOR_SVG}}"
      - magick {{.PIANTOR_SVG}} {{.PIANTOR_JPG}}
      - echo "✅ {{.PIANTOR_JPG}}"

  draw:
    desc: Generate all SVG diagrams
    deps:
      - draw-glove80
      - draw-corne
      - draw-piantor

  # ============================================================================
  # Build Tasks
  # ============================================================================

  build-glove80:
    desc: Build Glove80 firmware
    cmds:
      - ./build glove80
      - echo "✅ Glove80 firmware built"

  build-corne:
    desc: Build Corne firmware
    cmds:
      - ./build corne
      - echo "✅ Corne firmware built"

  build-piantor:
    desc: Build Piantor firmware
    cmds:
      - ./build piantor
      - echo "✅ Piantor firmware built"

  build:
    desc: Build all firmwares
    deps:
      - build-glove80
      - build-corne
      - build-piantor

  # ============================================================================
  # Sync Workflows (align + draw + build)
  # ============================================================================

  sync-glove80:
    desc: Align + draw + build (Glove80)
    cmds:
      - task: align-glove80
      - task: draw-glove80
      - task: build-glove80
      - echo "✅ Glove80 sync complete"

  sync-corne:
    desc: Align + draw + build (Corne)
    cmds:
      - task: align-corne
      - task: draw-corne
      - task: build-corne
      - echo "✅ Corne sync complete"

  sync-piantor:
    desc: Align + draw + build (Piantor)
    cmds:
      - task: align-piantor
      - task: draw-piantor
      - task: build-piantor
      - echo "✅ Piantor sync complete"

  sync:
    desc: Align + draw + build (all keyboards)
    cmds:
      - task: align
      - task: draw
      - task: build
      - echo "✅ Sync complete"

  # ============================================================================
  # Testing Tasks
  # ============================================================================

  test:
    desc: Run test suite
    cmds:
      - uv run pytest {{.PYTEST_FILE}} -v

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - uv run pytest {{.PYTEST_FILE}} -vvv --tb=long

  # ============================================================================
  # Cleanup Tasks
  # ============================================================================

  clean:
    desc: Remove temp files and UF2s
    cmds:
      - find . -name "*.pyc" -delete 2>/dev/null || true
      - find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.tmp" -delete 2>/dev/null || true
      - find . -name "*~" -delete 2>/dev/null || true
      - rm -f ./*.uf2 2>/dev/null || true
      - echo "✅ Cleaned"
